#!/usr/bin/env python
"""Sample the 50-question study set from the prepared Alodokter questions.

Selection rule (documented for the methods section):
  1. uniform random sample of 50 threads from questions_alodokter.jsonl,
     seeded (20260628) and without replacement — every real question has the
     same inclusion probability, preserving the natural topic mix;
  2. the 50 are sorted by question length (e5 query tokens when present, else
     characters) and snake-assigned (1-2-2-1) to two 25-question blocks, so the
     blocks are balanced on length as a proxy for difficulty (the study's
     counterbalancing crossover needs comparable blocks);
  3. within each block the presentation order is shuffled with the same seeded
     RNG; study ids Q01..Q25 = block 1, Q26..Q50 = block 2.

The study protocol still requires a manual scope screen (depression-relevant,
answerable within the guideline) before finalising; replace a question by
re-running with --exclude <question_id ...> so the rule stays reproducible.

    python scripts/sample_alodokter_questions.py
    python scripts/sample_alodokter_questions.py --n 50 --exclude alo_0123
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path
from statistics import mean

ROOT = Path(__file__).resolve().parents[1]
SEED = 20260628


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="sample-alodokter-questions", description=__doc__)
    ap.add_argument("--questions", default=str(ROOT / "data" / "derived" / "questions_alodokter.jsonl"))
    ap.add_argument("--out", default=str(ROOT / "data" / "derived" / "questions_alodokter_sample50.jsonl"))
    ap.add_argument("--report", default=str(ROOT / "outputs" / "analysis" / "alodokter_sample50_report.md"))
    ap.add_argument("--n", type=int, default=50)
    ap.add_argument("--seed", type=int, default=SEED)
    ap.add_argument("--exclude", nargs="*", default=[],
                    help="question_ids ruled out by the manual scope screen")
    args = ap.parse_args(argv)

    rows = [json.loads(l) for l in open(args.questions, encoding="utf-8")]
    pool = [r for r in rows if r["question_id"] not in set(args.exclude)]
    if len(pool) < args.n:
        raise SystemExit(f"pool ({len(pool)}) smaller than sample size ({args.n})")

    rng = random.Random(args.seed)
    sample = rng.sample(pool, args.n)

    size = lambda r: r.get("e5_query_tokens") or len(r["question"])
    sample.sort(key=size)
    half = args.n // 2
    blocks: dict[int, list[dict]] = {1: [], 2: []}
    for i, r in enumerate(sample):           # 1-2-2-1 snake: balances a sorted list
        blocks[1 if i % 4 in (0, 3) else 2].append(r)
    while len(blocks[1]) > half:             # odd tail correction, deterministic
        blocks[2].append(blocks[1].pop())

    out_rows = []
    for b in (1, 2):
        rng.shuffle(blocks[b])
        for r in blocks[b]:
            rec = dict(r)
            rec["block"] = b
            rec["study_id"] = f"Q{len(out_rows) + 1:02d}"
            out_rows.append(rec)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        for rec in out_rows:
            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")

    stats = {b: [size(r) for r in blocks[b]] for b in (1, 2)}
    over = [r["study_id"] + "/" + r["question_id"] for r in out_rows if r.get("over_query_cap")]
    lines = ["# Alodokter 50-question study sample\n",
             f"_Generated by `scripts/sample_alodokter_questions.py` (seed {args.seed})._\n",
             f"- pool: {len(pool)} questions ({len(args.exclude)} excluded by scope screen: "
             f"{', '.join(args.exclude) if args.exclude else 'none yet — screen pending'})",
             f"- sampled: **{len(out_rows)}** -> `{out}`",
             f"- block balance (question size, tokens): block 1 mean {mean(stats[1]):.0f} "
             f"(n={len(stats[1])}), block 2 mean {mean(stats[2]):.0f} (n={len(stats[2])})",
             f"- over the 512-token query cap in sample: {len(over)} ({', '.join(over) or '—'})",
             "\n> Blocks are balanced on length as a difficulty proxy (no taxonomy labels "
             "exist for real questions). Assignment: Q01-Q25 = block 1, Q26-Q50 = block 2; "
             "presentation order within a block is seeded-random. The counterbalancing "
             "crossover (counselor 1: C then B; counselor 2: B then C) uses these blocks."]
    report = Path(args.report)
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    print(f"\n[wrote {out} and {report}]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
