#!/usr/bin/env python
"""Validate a question set against the gold passages, print and optionally save a report.

    python scripts/validate_questions.py [questions.jsonl] [out=outputs/analysis/report.md]

Defaults: questions = data/derived/questions_candidate.jsonl; no file written unless
`out=` is given. Use it on the human-validated data/derived/questions_gold.jsonl too.
Exits non-zero on any schema / passage-reference error.
"""

from __future__ import annotations

import sys
from pathlib import Path

from depression_rag.evaluation import build_gold_passages, load_questions, validate_questions

ROOT = Path(__file__).resolve().parents[1]
TARGET_MIN = 100  # generation floor stated in the QA-generation prompt


def main() -> None:
    qpath = ROOT / "data" / "derived" / "questions_candidate.jsonl"
    out: Path | None = None
    for arg in sys.argv[1:]:
        if arg.startswith("out="):
            out = Path(arg[4:])
        else:
            qpath = Path(arg)

    gp = build_gold_passages(
        ROOT / "configs" / "gold_passages.yaml",
        ROOT / "data" / "derived" / "segments.jsonl",
        ROOT / "data" / "derived" / "cleaned_text.txt",
    )
    concept_by_passage = {p.passage_id: p.concept for p in gp.passages}

    questions = load_questions(qpath)
    v = validate_questions(questions, concept_by_passage)

    lines: list[str] = []
    def emit(s: str = "") -> None:
        print(s)
        lines.append(s)

    emit("# Question-set validation report")
    emit(f"\n_Generated by `scripts/validate_questions.py`._\n")
    emit(f"- file: `{qpath}`")
    emit(f"- questions: **{v.n}** "
         f"({'>= ' + str(TARGET_MIN) + ' OK' if v.n >= TARGET_MIN else '< ' + str(TARGET_MIN) + ' BELOW FLOOR'})")
    emit(f"- gold passages covered: {v.passages_covered}/{v.passages_total}")

    emit("\n## by question_type\n\n| question_type | n |\n|---|--:|")
    for k in sorted(v.by_type):
        emit(f"| {k} | {v.by_type[k]} |")

    emit("\n## by difficulty\n\n| difficulty | n |\n|---|--:|")
    for k in sorted(v.by_difficulty):
        emit(f"| {k} | {v.by_difficulty[k]} |")

    emit("\n## by gold concept (passage mentions)\n\n| concept | n |\n|---|--:|")
    for k in sorted(v.by_concept):
        emit(f"| {k} | {v.by_concept[k]} |")

    if v.ok:
        emit("\n**VALIDATION OK**")
    else:
        emit(f"\n**VALIDATION FAILED ({len(v.errors)} errors):**")
        for e in v.errors:
            emit(f"- {e}")

    if out is not None:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"\n[written: {out}]")

    if not v.ok:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
